version: "3"
services:
  app:
    build: .
    command: node server
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    ports:
      - "3006:3006"
    volumes:
      - /node_modules

  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - "27017:27017"